import Head from 'next/head';
import Hero from '@/components/Hero';
import Layout from '@/components/Layout';
import WeatherWeekly from '@/components/Weather/WeatherWeekly';
import WeatherHighlights from '@/components/Weather/WeatherHighlights';
import { getDailyWeather } from '@/utils/getDailyWeather';
import data from '@/utils/getDailyWeather';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<Hero />
				<div className="lg:min-h-fit lg:w-2/3">
					<WeatherWeekly />
					<WeatherHighlights />
				</div>
			</Layout>
		</>
	);
}
